/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20Test1Sol from "./ERC20test1.sol";
export type { erc20Test1Sol };
export type { ERC20 } from "./ERC20";
export type { ERC20test2 } from "./ERC20test2";
