/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc20Test1Sol from "./ERC20test1.sol";
export { ERC20__factory } from "./ERC20__factory";
export { ERC20test2__factory } from "./ERC20test2__factory";
